### ISSUE TITLE
Nueva entidad Invitado

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g2_sf#3]
Crear la entidad `Invitado` en el paquete `entity` con los siguientes atributos:

* id: Long
* nombre: String
* apellido: String
* dni: String
* telefono: String
* correo: String
* tipoInvitado: String (por ejemplo, "amigo", "plomero")

**Tareas:**

1. Crear la clase `Invitado`.
2. Definir los atributos mencionados.
3. Agregar las anotaciones JPA necesarias.
4. Realizar una captura de pantalla de la tabla generada en la base de datos y adjuntarla al pull request.

**Comment by enzo2001v** [comment]
![Issues 1 - invitado](https://github.com/ahumadamob/2024_gc_p2_g2_sf/assets/91561353/a4095b69-95aa-4a09-aa00-863e2e10122f)

**Comment by ahumadamob** [comment]
Crea estas correcciones en 3-nueva-entidad-invitado-correct porque habias hecho git add .
