### ISSUE TITLE
Final Noviembre Chiara Baldasarre 

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g2_sf#56]
**Ejercicio de Programación en Spring Boot**

Objetivo: Desarrollar un endpoint en Spring Boot que se conecte a una base de datos MySQL y devuelva un listado filtrado, cumpliendo con los siguientes requerimientos.

### Lineamientos generales:
1. **Conexión a una nueva base de datos MySQL:** 
   - Configura tu proyecto para conectarse a una base de datos nueva en MySQL llamada **baldasarrec**.

2. **Endpoint GET:**
   - Desarrolla un endpoint GET que devuelva todas las familias cuya propiedad `relacion` sea igual a "Padre" o "Madre". La URL del endpoint será:

   ```
   /familias/padresMadres
   ```

   El método en el repositorio que debes usar para realizar el filtro es el siguiente:

   ```java
   List<Familia> findByRelacionIn(List<String> relaciones);
   ```

3. **Nueva propiedad en la entidad:**
   - Añade una nueva propiedad **boolean** a la entidad `Familia` llamada `viveEnPropiedad`. Esta propiedad indicará si el miembro de la familia vive en la propiedad familiar o no. Recuerda crear los métodos `getter` y `setter` para esta nueva propiedad.

4. **Servicio:**
   - Implementa la lógica del servicio para manejar el listado filtrado y manejar la nueva propiedad `viveEnPropiedad`.

5. **Controlador:**
   - El controlador debe manejar el endpoint GET `/familias/padresMadres` y devolver el listado filtrado utilizando un **DTO** (Data Transfer Object) que incluya la nueva propiedad `viveEnPropiedad`.

### Requisitos:
- Cada endpoint deberá responder utilizando un DTO.
- El DTO deberá incluir la nueva propiedad `viveEnPropiedad` que agregaste a la entidad.
- El código deberá estar bien comentado, explicando cada parte del proceso.
- Asegúrate de que el listado filtrado funcione correctamente a través de pruebas en Postman.

### Entrega:
- El código fuente deberá ser subido a un repositorio en GitHub.
- Realiza pruebas con Postman y adjunta capturas de pantalla con las peticiones y respuestas.

**Comment by ChiaraBaldasarre** [comment]
![image](https://github.com/user-attachments/assets/3e6fac76-4e5c-4573-ba6f-6aa1d53d893f)

![image](https://github.com/user-attachments/assets/801e8c12-8331-4e2c-8309-c0df773f1466)
