### ISSUE TITLE
Nueva entidad Visita

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g2_sf#8]
Crear la entidad `Visita` en el paquete `entity` con los siguientes atributos:

* id: Long
* invitado: String
* fechaVisita: LocalDate
* horaIngreso: LocalTime
* horaEgreso: LocalTime
* propiedadVisitada: String

**Tareas:**

1. Crear la clase `Visita`.
2. Definir los atributos mencionados.
3. Agregar las anotaciones JPA necesarias.
4. Realizar una captura de pantalla de la tabla generada en la base de datos y adjuntarla al pull request.

**Comment by enzo2001v** [comment]
![image](https://github.com/ahumadamob/2024_gc_p2_g2_sf/assets/91561353/d7f72377-462d-4c7a-8cb3-d302c9e75daf)
