### ISSUE TITLE
Nueva entidad Ingreso Egreso

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g2_sf#9]
Issue 9: Crear Entidad Registro de Ingreso y Egreso

**Descripción:**Crear la entidad `RegistroDeIngresoYEgreso` en el paquete `entity` con los siguientes atributos:

* id: Long
* fechaIngreso: LocalDate
* horaIngreso: LocalTime
* fechaEgreso: LocalDate
* horaEgreso: LocalTime
* guardiaDeSeguridad: String
* visita: String
* observaciones: String

**Tareas:**

1. Crear la clase `RegistroDeIngresoYEgreso`.
2. Definir los atributos mencionados.
3. Agregar las anotaciones JPA necesarias.
4. Realizar una captura de pantalla de la tabla generada en la base de datos y adjuntarla al pull request.

Estos issues pueden ser creados en GitHub para guiar el desarrollo de las entidades necesarias en tu proyecto.

**Comment by ChiaraBaldasarre** [comment]
![image](https://github.com/ahumadamob/2024_gc_p2_g2_sf/assets/133431099/a91ec80a-55fc-499e-86bb-c3ca0ec10f65)

**Comment by ahumadamob** [comment]
Falta el pull request de esta entidad
